on:
  push:
    branches:
      - master
name: Deploy to Production https://vvce.acm.org
jobs:
 web-deploy:
  name: Production
  runs-on: ubuntu-latest
  steps:
    - name: Update Code
      uses: actions/checkout@v2.3.2

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.vvce.hosting.acm.org
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /public_html/ 